events {
	worker_connections 768;
	# multi_accept o
}
worker_processes  1;

http {
    include       mime.types;
    default_type  application/octet-stream;
    client_header_buffer_size 16k;
    large_client_header_buffers 4 64k;

    sendfile        on;
    keepalive_timeout  65;

    server {
        listen       80;
        server_name  localhost;

        # 设置静态资源根目录，指向项目的 static 文件夹
        root   /var/www/dist/;
        index  index.html index.htm;

        # 根目录配置：支持 .html 后缀自动补全/隐藏
        location / {
            try_files $uri $uri.html $uri/ =404;
        }

        location /api/ {
            proxy_pass http://localhost:7510/api/;
        }
    }
}

